### ISSUE TITLE
Add PHP 5.5 Compatibility

### ISSUE THREAD

**Issue by joshdifabio** [pascaldevink/shortuuid#2]
It would be really useful to be able to use this library in PHP 5.5 projects. Unless I am mistaken, the only reason to require 5.6 is the dependency on PHP Unit 5.0. Would you accept a PR which changes the PHP version constraint to `>=5.5` and the PHP Unit constraint to `>=4.0,<6`?

**Comment by garak** [comment]
:+1:

**Comment by OndraM** [comment]
:+1:
We are still on PHP 5.5 as well :-/.

**Comment by snapshotpl** [comment]
:+1:

**Comment by andersonamuller** [comment]
:+1:

**Comment by OndraM** [comment]
For anyone interested I've prepared [PHP 5.5 compatible fork](https://github.com/OndraM/shortuuid) and published it to [Packagist](https://packagist.org/packages/ondram/shortuuid-php55) to to make it easily installable via Composer.
I do not intend to maintain it in longer term, I hope we will switch to PHP 5.6+ asap (an you should too :) ).

`composer require ondram/shortuuid-php55`

**Comment by pascaldevink** [comment]
Thanks @OndraM for porting it back to PHP 5.5. I for one won't ever support it, because I only want to support the actively supported versions of PHP. For me, this is my way of hopefully pushing people to continuously upgrade to the latest version of PHP.

Probably going to drop PHP 5.6 support as well at the beginning of 2017.
